swagger: '2.0'
info:
  title: Lambda Test
  x-ibm-name: publish-test-lambda
  version: 1.0.1
x-ibm-configuration:
  cors:
    enabled: true
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
      - set-variable:
          version: 2.0.0
          title: set-variable
          actions:
            - set: message.body
              value: RESPONSE
              type: string
      - aws-lambda:
          version: 1.0.0
          title: lambda
          aws_assume_role_arn: arn:aws:iam::258263412479:role/APIC-Cloud-lambda
          function_name: echo
          aws_region: us-east-1             
basePath: /publish-test
paths:
  /:
    get:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
schemes:
  - https